using System.Globalization;
using System.Windows.Markup;

namespace SocLucia.Localization;

/// <summary>
/// Textos de la aplicacion en español e ingles (constitucion, seccion 7). Ningun texto va en el
/// XAML ni en el codigo: todo pasa por aqui.
/// </summary>
public static class Loc
{
    private static readonly Dictionary<string, string> English = new()
    {
        ["AppTitle"] = "sOC Lucia",
        ["AboutTitle"] = "About",
        ["AboutTooltip"] = "About",
        ["AboutDescription"] = "A private AI that runs on this PC. Ask anything: the answer is generated here, and nothing leaves your computer.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contact",
        ["WriteAuthor"] = "Write to the author",
        ["ContactHint"] = "Suggestions, bugs and ideas: all of it gets read.",
        ["LanguageTitle"] = "Language",
        ["LanguageHint"] = "The language applies right away.",
        ["Privacy"] = "Privacy",
        ["PrivacyText"] = "Conversations and the AI stay on this PC, in your user profile; the AI runs here and answers here. The network is used only to download the engine (llama.cpp) and the AI you choose from Hugging Face, and only when you ask for it. No account, no ads, no trackers, no analytics. The optional door for code editors listens on this computer only and needs a token.",
        ["License"] = "License",
        ["LicenseText"] = "Free software under the MIT licence. The engine is llama.cpp (MIT), downloaded at first use. Each AI carries its own licence, shown before the download.",
        ["LicenseLine"] = "MIT License · Copyright © 2026 Socratic",
        ["LegalTitle"] = "Legal notice",
        ["LegalText1"] = "This software is provided \"as is\", without warranty of any kind, express or implied. AI answers can be wrong: check them before acting on them.",
        ["LegalText2"] = "In no event shall the authors be liable for any claim, damages or other liability arising from the use of this software. By using it, the user releases the developer from all liability.",
        ["WarningText"] = "⚠️ Use at your own risk",
        ["Close"] = "Close",
        ["LanguageTooltip"] = "Español / English",

        ["NewChat"] = "New conversation",
        ["Conversations"] = "Conversations",
        ["DeleteChat"] = "Delete conversation",
        ["DeleteChatConfirm"] = "Delete this conversation? This cannot be undone.",
        ["RenameChat"] = "Rename",
        ["RenamePrompt"] = "Title of the conversation",
        ["ComposerHint"] = "Ask something… (Enter sends, Shift+Enter new line)",
        ["Send"] = "Send",
        ["Stop"] = "Stop",
        ["Copy"] = "Copy",
        ["Copied"] = "Copied",
        ["Thinking"] = "Reasoning",
        ["Settings"] = "Settings",
        ["EmptyTitle"] = "Ask the AI on this PC",
        ["EmptyHint"] = "Nothing you write leaves this computer. The first answer after opening takes a while: the AI is loading into memory.",
        ["EngineNoModel"] = "No AI installed yet",
        ["EngineDownloading"] = "Downloading the engine…",
        ["EngineStarting"] = "Loading the AI into memory…",
        ["EngineReady"] = "AI ready",
        ["EngineStopped"] = "AI stopped",
        ["EngineError"] = "The AI could not start",
        ["NoModelYet"] = "No AI installed yet. Choose one in Settings.",
        ["EngineExited"] = "The engine exited with code {0}. See the engine log in Settings.",
        ["EngineTimeout"] = "The engine did not answer in time. See the engine log in Settings.",
        ["AnswerFailed"] = "Could not answer: {0}",

        // Ajustes
        ["SettingsTitle"] = "Settings",
        ["ModelTitle"] = "The AI",
        ["ModelNone"] = "No AI installed. Pick one below, or import a GGUF file you already have.",
        ["ModelCurrent"] = "Installed: {0}",
        ["ModelLicenseLine"] = "Licence: {0}",
        ["ModelFile"] = "File: {0}",
        ["ModelRam"] = "This PC has {0} of memory. Only the AIs that fit are shown.",
        ["ModelRecommended"] = "Recommended",
        ["ModelInstall"] = "Install",
        ["ModelInstalling"] = "Downloading {0}… {1}",
        ["ModelImport"] = "Import a GGUF file…",
        ["ModelImportHint"] = "Any llama.cpp GGUF (one file, no shards). It is used in place: it is not copied.",
        ["ModelCancel"] = "Cancel download",
        ["ModelInstalled"] = "Installed. The next question will use it.",
        ["ModelSize"] = "{0} download",
        ["CatalogBig"] = "The most capable one. Needs a PC with plenty of memory.",
        ["CatalogMid"] = "Good answers and a manageable download.",
        ["CatalogSmall"] = "Fast, many languages, fits an 8 GB PC.",
        ["CatalogTiny"] = "Small file, short answers.",
        ["InstructionsTitle"] = "Standing instructions",
        ["InstructionsHint"] = "Sent with every conversation: tone, language, what the AI should never do.",
        ["InstructionsPlaceholder"] = "For example: answer in Spanish, briefly, and say when you are not sure.",
        ["ThinkingTitle"] = "Let the AI reason before answering",
        ["ThinkingHint"] = "Slower; sometimes better on hard questions. The reasoning is shown folded above the answer.",
        ["ThinkToggle"] = "Think",
        ["Attach"] = "Attach files or images",
        ["AttachFilter"] = "Files and images|*.*",
        ["PastedImage"] = "pasted image",
        ["AttachUnsupported"] = "{0} does not look like a text file or an image, so the AI could not read it.",
        ["AttachTooBig"] = "{0} is larger than 20 MB.",
        ["Remove"] = "Remove",
        ["Open"] = "Open",
        ["AttachedOnly"] = "(see the attached files)",
        ["VisionOn"] = "sees images",
        ["NoVisionModel"] = "This AI cannot see images. Install one with vision (Gemma 4 12B, Qwen3.5 4B or 2B, Ministral 3 8B, Qwen3.8 27B) in Settings › The AI, and attach the picture again.",
        ["VisionTitle"] = "Vision",
        ["VisionOffer"] = "You attached an image, but {0} has not got its vision part yet. Download it now (a few hundred MB, once)? The AI will then understand pictures.",
        ["VisionDownloading"] = "Downloading the vision part of the AI…",
        ["OpenImage"] = "Open",
        ["SaveImage"] = "Save as…",
        ["ImageEngineDownloading"] = "Downloading the image engine (stable-diffusion.cpp)…",
        ["ImageModelDownloading"] = "Downloading {0} (1.7 GB, once)…",
        ["ImageGenerating"] = "Generating the image… (the chat AI pauses meanwhile)",
        ["ImageGeneratingCpu"] = "Generating the image on the CPU (the graphics card could not; this takes a few minutes)…",
        ["ImageFailed"] = "The image could not be generated. See logs\\engine.log.",
        ["ImagesTitle"] = "Images",
        ["ImagesHint"] = "Ask for a picture in the chat («draw a lighthouse at dusk») and the AI generates it on this PC with stable-diffusion.cpp (MIT) and Stable Diffusion 1.5. Nothing goes to the internet. While an image renders, the chat AI is paused (they do not both fit in the graphics memory).",
        ["ImagesInstalling"] = "Downloading…",
        ["ImagesInstalled"] = "Installed: {0} ({1}; {2:0.0} GB on disk).",
        ["ImagesNotInstalled"] = "Not installed: {0} (≈ {1:0.0} GB). It is also downloaded the first time you ask for a picture.",
        ["ImagesInstall"] = "Install now",
        ["ImagesFolder"] = "Open the images folder",
        ["ImagesRemove"] = "Remove",
        ["ImagesRemoveConfirm"] = "Remove the image engine and model? They are downloaded again if you ask for a picture.",
        ["FontSizeTitle"] = "Chat text size",
        ["DoorTitle"] = "Code editors (VS Code)",
        ["DoorHint"] = "Lets a code editor on this PC program with this AI. Opens a local door (this computer only), compatible with the OpenAI API and protected with a token. Nothing leaves the PC.",
        ["DoorEnable"] = "Turn on the door for editors",
        ["DoorUrl"] = "Address",
        ["DoorToken"] = "Token",
        ["DoorPort"] = "Port",
        ["DoorNewToken"] = "New token",
        ["DoorListening"] = "Listening.",
        ["DoorStopped"] = "Stopped.",
        ["DoorHow"] = "In VS Code: install the extension from the release (\"sOC Lucia Code\", .vsix) and paste the token in its settings; or point Continue, Cline or any OpenAI-compatible client at this address and token.",
        ["DoorBadToken"] = "Missing or wrong token. Copy it from sOC Lucia > Settings > Code editors.",
        ["DiagnosticsTitle"] = "Diagnostics",
        ["OpenEngineLog"] = "Open the engine log",
        ["OpenDataFolder"] = "Open the data folder",
        ["Accelerator"] = "Engine: llama.cpp {0} · {1}",
        ["WorkMode"] = "Agent mode: the AI works through the task with tools (commands, files, internet…), step by step, asking for permission",
        ["WorkTitle"] = "Agent mode",
        ["WorkHint"] = "With \"Agent\" selected above the composer, the AI can use this PC: run commands, read and write files, download from the internet, use the clipboard and open things. Each action is shown before it happens and you approve it, unless you decide otherwise below. Everything it does is logged.",
        ["WorkFolder"] = "Working folder",
        ["WorkFolderPick"] = "Choose folder",
        ["OpenCommandLog"] = "Open the action log",
        ["CommandTitle"] = "Run this command?",
        ["CommandIntro"] = "The AI wants to run this on your PC:",
        ["CommandFolder"] = "In: {0}",
        ["CommandAutoApprove"] = "Don't ask again in this conversation",
        ["CommandRun"] = "Run (Ctrl+Enter)",
        ["CommandRunning"] = "Working…",
        ["CommandOutput"] = "Result",
        ["WindowsSection"] = "Windows",
        ["TrayOnMinimize"] = "Keep in the notification area when minimised",
        ["TrayOnMinimizeHint"] = "Click the tray icon to bring it back; right-click for Open or Exit.",
        ["StartWithWindows"] = "Start with Windows",
        ["StartWithWindowsHint"] = "Starts hidden in the notification area when you sign in.",
        ["TrayOpen"] = "Open",
        ["TrayExit"] = "Exit",
        ["ModelsFolder"] = "Models folder",
        ["ModelsFolderPick"] = "Choose another folder (the models are moved there)",
        ["ModelsFolderHint"] = "The downloaded AIs weigh gigabytes: they can live on another drive. Changing the folder moves the ones you already have.",
        ["ModelsFolderMoveConfirm"] = "Move {0} model file(s) to {1}? The AI stops while they move.",
        ["ModelsFolderMoving"] = "Moving…",
        ["ModelsFolderMovingFile"] = "Moving {0}… {1}",
        ["ModelsFolderMoved"] = "Moved.",
        ["ModelsFolderInside"] = "The new folder cannot be inside the current one.",
        ["ModelsInstalled"] = "Installed on this PC",
        ["ModelActive"] = "In use",
        ["ModelUse"] = "Use this AI",
        ["ModelDelete"] = "Delete this AI",
        ["ModelDeleteConfirm"] = "Delete {0} from the disk? You can download it again later.",
        ["EditQuestion"] = "Edit (copies it to the composer)",
        ["ResendQuestion"] = "Send again",
        ["PcWithGpu"] = "This PC: {0} ({1} threads), {2} of RAM, {3} with {4} of video memory.",
        ["PcNoGpu"] = "This PC: {0} ({1} threads), {2} of RAM, no dedicated graphics card: the AI runs on the processor.",
        ["PcStarHint"] = "★ = optimal for this PC: fast and dependable. Only the AIs that fit in memory are listed.",
        ["FitOptimalGpu"] = "★ Optimal here: fits entirely in the graphics card.",
        ["FitOptimalCpu"] = "★ Optimal here: light enough to be fast on the processor.",
        ["FitOkGpu"] = "Works, but slower: part of it stays outside the graphics card.",
        ["FitOkCpu"] = "Works, but slower on the processor.",
        ["FitSlow"] = "Slow on this PC: it fits in memory, but answers will take a while.",
        ["PermSection"] = "Permissions",
        ["PermSectionHint"] = "What the AI may use on this PC in agent mode. \"Ask\" shows each action before it happens; \"Always\" skips the question; \"Never\" hides that resource from the AI.",
        ["PermAsk"] = "Ask",
        ["PermAllowAlways"] = "Always",
        ["PermDeny"] = "Never",
        ["Perm_Commands"] = "Commands",
        ["PermHint_Commands"] = "Run PowerShell command lines (programs, git, dotnet, python…).",
        ["Perm_FilesRead"] = "Read files",
        ["PermHint_FilesRead"] = "Read files, list and search folders.",
        ["Perm_FilesWrite"] = "Write files",
        ["PermHint_FilesWrite"] = "Create or overwrite files (notes, scripts, code, results).",
        ["Perm_Internet"] = "Internet",
        ["PermHint_Internet"] = "Download web pages or files (read only).",
        ["Perm_Clipboard"] = "Clipboard",
        ["PermHint_Clipboard"] = "Read or replace the text in the clipboard.",
        ["Perm_Apps"] = "Open things",
        ["PermHint_Apps"] = "Open a file, folder, program or web address with its usual program.",
        ["PermTitle"] = "Allow this?",
        ["PermIntro_Commands"] = "The AI wants to run this command on your PC:",
        ["PermIntro_FilesRead"] = "The AI wants to read this:",
        ["PermIntro_FilesWrite"] = "The AI wants to write this file:",
        ["PermIntro_Internet"] = "The AI wants to use the internet:",
        ["PermIntro_Clipboard"] = "The AI wants to use the clipboard:",
        ["PermIntro_Apps"] = "The AI wants to open this:",
        ["PermConversation"] = "Don't ask again for this in this conversation",
        ["PermAlways"] = "Always allow \"{0}\" (changeable in Settings > Permissions)",
        ["PermAllow"] = "Allow (Ctrl+Enter)",
        ["AskMode"] = "Questions",
        ["AskModeHint"] = "Questions mode: the AI answers; it uses the PC, your documents or the internet only when the question needs it (asking permission)",
        ["AgentMode"] = "Agent",
        ["ModelPick"] = "The AI that answers in this app (the ones installed; more in Settings)",
        ["FontSizeHint"] = "Size of the text in the conversation (questions and answers). The rest of the app does not change.",
        ["CatalogHf"] = "From Hugging Face",
        ["SearchHf"] = "Find more AIs on Hugging Face",
        ["SearchHfTip"] = "Name or family: llama, mistral, gemma, qwen, deepseek, spanish…",
        ["SearchHfHint"] = "Searches huggingface.co by name, family or keyword (images, video, speech…), weighs each GGUF and tells you how it would run on this PC (★ = optimal). Untick the box to see every kind of model, with a link; only single-file GGUF text models install here (Q4_K_M is chosen).",
        ["SearchHfSearching"] = "Searching Hugging Face and weighing each result…",
        ["SearchHfNone"] = "Nothing found. Try another name, a family (llama, qwen, gemma…) or a keyword.",
        ["SearchHfFound"] = "{0} results: {1} optimal for this PC, {2} this app can run. Order: optimal first, then the rest by downloads.",
        ["SearchHfError"] = "Could not search: {0}",
        ["SearchHfStats"] = "{0} downloads · {1} likes",
        ["SearchHfGated"] = "requires accepting a licence on huggingface.co (the download may fail)",
        ["InternetTitle"] = "Let the AI access the internet",
        ["InternetHint"] = "In both modes it can search the web and read pages when a question needs current or verifiable information; each search and page shows up in the conversation. Nothing else leaves the PC. Unticked, the AI works offline.",
        ["DocsTitle"] = "Your documents",
        ["DocsHint"] = "Put text files, Markdown, CSV, JSON, code, HTML or Word (.docx) in this folder and the AI takes them into account (it also saves here the documents you ask it to write, .docx included): with each question it receives the passages that match it, and it can list and read them whole. Nothing is indexed anywhere else.",
        ["DocsPick"] = "Choose another folder",
        ["DocsOpen"] = "Open the folder",
        ["DocsCount"] = "{0} document(s) taken into account.",
        ["DocsMissing"] = "The folder does not exist yet: open it to create it and drop files in.",
        ["MemoryTitle"] = "What the AI knows about you",
        ["MemoryHint"] = "Short facts the AI saves when you tell it something lasting about yourself (name, work, preferences…). They are sent with every conversation so it does not ask again. Stored only on this PC, in memory.json.",
        ["MemoryEnable"] = "Let the AI remember things about me",
        ["MemoryEmpty"] = "Nothing yet. It will appear here as you talk.",
        ["MemoryForget"] = "Forget this",
        ["MemoryClear"] = "Forget everything",
        ["MemoryClearConfirm"] = "Delete everything the AI knows about you? It starts from scratch in the next conversation.",
        ["CatalogLabel"] = "Catalogue",
        ["SearchOnlyGguf"] = "Only AIs this app can run (GGUF text models)",
        ["SearchNotSingleGguf"] = "GGUF split in several files: not installable from here.",
        ["SearchNotGguf"] = "Not a GGUF: this app cannot run it (it needs Python or another program).",
        ["SearchNotGgufKind"] = "Type: {0}. Not a GGUF text model: this app cannot run it (it needs Python or another program).",
        ["SearchOpenHf"] = "Open on huggingface.co",
        ["FitTooBig"] = "Does not fit in this PC's memory.",
        ["SaveCode"] = "Save as a file",
        ["OpenDocument"] = "Open {0}",
        ["TasksTitle"] = "Scheduled tasks",
        ["TasksHint"] = "Ask the AI in the chat, e.g. \"every morning at 9 summarise my documents folder\" or \"remind me on Friday at 18:00 to send the report\": it schedules it and it runs by itself as a new conversation (⏰), while the app is open (also in the tray). Unattended runs only use the resources set to Always in Permissions.",
        ["TasksEmpty"] = "No scheduled tasks.",
        ["TaskEnabled"] = "On / off",
        ["TaskNext"] = "next {0}",
        ["TaskLast"] = "last {0}",
        ["TaskDelete"] = "Delete the task",
        ["TaskDone"] = "Done. Open the app to see the result.",
        ["Save"] = "Save",
        ["Saved"] = "Saved",
        ["Ok"] = "OK",
        ["Cancel"] = "Cancel",
        ["Yes"] = "Yes",
        ["No"] = "No",
        ["Error"] = "Error",
    };

    private static readonly Dictionary<string, string> Spanish = new()
    {
        ["AppTitle"] = "sOC Lucia",
        ["AboutTitle"] = "Acerca de",
        ["AboutTooltip"] = "Acerca de",
        ["AboutDescription"] = "Una IA privada que se ejecuta en este PC. Pregunta lo que quieras: la respuesta se genera aquí y nada sale de tu ordenador.",
        ["Publisher"] = "Socratic",
        ["Contact"] = "Contacto",
        ["WriteAuthor"] = "Escribir al autor",
        ["ContactHint"] = "Sugerencias, errores e ideas: se lee todo.",
        ["LanguageTitle"] = "Idioma",
        ["LanguageHint"] = "El idioma se aplica de inmediato.",
        ["Privacy"] = "Privacidad",
        ["PrivacyText"] = "Las conversaciones y la IA se quedan en este PC, en tu perfil de usuario; la IA se ejecuta aquí y responde aquí. La red solo se usa para descargar el motor (llama.cpp) y la IA que elijas de Hugging Face, y solo cuando lo pides. Sin cuenta, sin anuncios, sin rastreadores ni analítica. La puerta opcional para editores de código solo escucha en este equipo y exige un token.",
        ["License"] = "Licencia",
        ["LicenseText"] = "Software libre bajo licencia MIT. El motor es llama.cpp (MIT), que se descarga al primer uso. Cada IA trae su propia licencia, que se muestra antes de descargarla.",
        ["LicenseLine"] = "MIT License · Copyright © 2026 Socratic",
        ["LegalTitle"] = "Aviso legal",
        ["LegalText1"] = "Este software se entrega «tal cual», sin garantías de ningún tipo, expresas o implícitas. Las respuestas de una IA pueden ser erróneas: compruébalas antes de actuar.",
        ["LegalText2"] = "En ningún caso los autores serán responsables de reclamaciones, daños u otras responsabilidades derivadas del uso de este software. Al usarlo, el usuario exime al desarrollador de toda responsabilidad.",
        ["WarningText"] = "⚠️ Uso bajo su propio riesgo",
        ["Close"] = "Cerrar",
        ["LanguageTooltip"] = "Español / English",

        ["NewChat"] = "Nueva conversación",
        ["Conversations"] = "Conversaciones",
        ["DeleteChat"] = "Borrar conversación",
        ["DeleteChatConfirm"] = "¿Borrar esta conversación? No se puede deshacer.",
        ["RenameChat"] = "Renombrar",
        ["RenamePrompt"] = "Título de la conversación",
        ["ComposerHint"] = "Pregunta algo… (Enter envía, Mayús+Enter salto de línea)",
        ["Send"] = "Enviar",
        ["Stop"] = "Parar",
        ["Copy"] = "Copiar",
        ["Copied"] = "Copiado",
        ["Thinking"] = "Razonamiento",
        ["Settings"] = "Ajustes",
        ["EmptyTitle"] = "Pregunta a la IA de este PC",
        ["EmptyHint"] = "Nada de lo que escribas sale de este ordenador. La primera respuesta tras abrir tarda un poco: la IA se está cargando en memoria.",
        ["EngineNoModel"] = "Sin IA instalada",
        ["EngineDownloading"] = "Descargando el motor…",
        ["EngineStarting"] = "Cargando la IA en memoria…",
        ["EngineReady"] = "IA lista",
        ["EngineStopped"] = "IA parada",
        ["EngineError"] = "La IA no ha podido arrancar",
        ["NoModelYet"] = "Todavía no hay ninguna IA instalada. Elige una en Ajustes.",
        ["EngineExited"] = "El motor ha terminado con el código {0}. Mira el registro del motor en Ajustes.",
        ["EngineTimeout"] = "El motor no ha respondido a tiempo. Mira el registro del motor en Ajustes.",
        ["AnswerFailed"] = "No se ha podido responder: {0}",

        ["SettingsTitle"] = "Ajustes",
        ["ModelTitle"] = "La IA",
        ["ModelNone"] = "No hay ninguna IA instalada. Elige una de abajo o importa un fichero GGUF que ya tengas.",
        ["ModelCurrent"] = "Instalada: {0}",
        ["ModelLicenseLine"] = "Licencia: {0}",
        ["ModelFile"] = "Fichero: {0}",
        ["ModelRam"] = "Este PC tiene {0} de memoria. Solo se muestran las IA que caben.",
        ["ModelRecommended"] = "Recomendada",
        ["ModelInstall"] = "Instalar",
        ["ModelInstalling"] = "Descargando {0}… {1}",
        ["ModelImport"] = "Importar un fichero GGUF…",
        ["ModelImportHint"] = "Cualquier GGUF de llama.cpp (un solo fichero, sin trozos). Se usa donde está: no se copia.",
        ["ModelCancel"] = "Cancelar la descarga",
        ["ModelInstalled"] = "Instalada. La siguiente pregunta ya la usará.",
        ["ModelSize"] = "{0} de descarga",
        ["CatalogBig"] = "La más capaz. Necesita un PC con mucha memoria.",
        ["CatalogMid"] = "Buenas respuestas con una descarga razonable.",
        ["CatalogSmall"] = "Rápida, muchos idiomas, cabe en un PC de 8 GB.",
        ["CatalogTiny"] = "Fichero pequeño, respuestas cortas.",
        ["InstructionsTitle"] = "Instrucciones fijas",
        ["InstructionsHint"] = "Van con cada conversación: tono, idioma, lo que la IA nunca debe hacer.",
        ["InstructionsPlaceholder"] = "Por ejemplo: responde en español, breve, y di cuándo no estás seguro.",
        ["ThinkingTitle"] = "Dejar que la IA razone antes de responder",
        ["ThinkingHint"] = "Más lento; a veces mejor en preguntas difíciles. El razonamiento sale plegado encima de la respuesta.",
        ["ThinkToggle"] = "Pensar",
        ["Attach"] = "Adjuntar ficheros o imágenes",
        ["AttachFilter"] = "Ficheros e imágenes|*.*",
        ["PastedImage"] = "imagen pegada",
        ["AttachUnsupported"] = "{0} no parece un fichero de texto ni una imagen; la IA no podría leerlo.",
        ["AttachTooBig"] = "{0} pasa de 20 MB.",
        ["Remove"] = "Quitar",
        ["Open"] = "Abrir",
        ["AttachedOnly"] = "(mira los ficheros adjuntos)",
        ["VisionOn"] = "ve imágenes",
        ["NoVisionModel"] = "Esta IA no ve imágenes. Instala una con visión (Gemma 4 12B, Qwen3.5 4B o 2B, Ministral 3 8B, Qwen3.8 27B) en Ajustes › La IA y vuelve a adjuntar la imagen.",
        ["VisionTitle"] = "Visión",
        ["VisionOffer"] = "Has adjuntado una imagen, pero {0} aún no tiene su parte de visión. ¿Descargarla ahora (unos cientos de MB, una sola vez)? Después la IA entenderá imágenes.",
        ["VisionDownloading"] = "Descargando la parte de visión de la IA…",
        ["OpenImage"] = "Abrir",
        ["SaveImage"] = "Guardar como…",
        ["ImageEngineDownloading"] = "Descargando el motor de imágenes (stable-diffusion.cpp)…",
        ["ImageModelDownloading"] = "Descargando {0} (1,7 GB, una sola vez)…",
        ["ImageGenerating"] = "Generando la imagen… (la IA del chat se pausa mientras tanto)",
        ["ImageGeneratingCpu"] = "Generando la imagen en la CPU (la gráfica no ha podido; tarda unos minutos)…",
        ["ImageFailed"] = "No se ha podido generar la imagen. Mira logs\\engine.log.",
        ["ImagesTitle"] = "Imágenes",
        ["ImagesHint"] = "Pide un dibujo en el chat («dibuja un faro al atardecer») y la IA lo genera en este PC con stable-diffusion.cpp (MIT) y Stable Diffusion 1.5. Nada sale a internet. Mientras se genera una imagen, la IA del chat se pausa (no caben las dos en la memoria de la gráfica).",
        ["ImagesInstalling"] = "Descargando…",
        ["ImagesInstalled"] = "Instalado: {0} ({1}; {2:0.0} GB en disco).",
        ["ImagesNotInstalled"] = "Sin instalar: {0} (≈ {1:0.0} GB). También se descarga la primera vez que pidas un dibujo.",
        ["ImagesInstall"] = "Instalar ahora",
        ["ImagesFolder"] = "Abrir la carpeta de imágenes",
        ["ImagesRemove"] = "Quitar",
        ["ImagesRemoveConfirm"] = "¿Quitar el motor y el modelo de imágenes? Se vuelven a descargar si pides un dibujo.",
        ["FontSizeTitle"] = "Tamaño de la letra del chat",
        ["DoorTitle"] = "Editores de código (VS Code)",
        ["DoorHint"] = "Deja que un editor de código de este PC programe con esta IA. Abre una puerta local (solo en este equipo), compatible con la API de OpenAI y protegida con un token. Nada sale del PC.",
        ["DoorEnable"] = "Activar la puerta para editores",
        ["DoorUrl"] = "Dirección",
        ["DoorToken"] = "Token",
        ["DoorPort"] = "Puerto",
        ["DoorNewToken"] = "Nuevo token",
        ["DoorListening"] = "Escuchando.",
        ["DoorStopped"] = "Parada.",
        ["DoorHow"] = "En VS Code: instala la extensión de la release («sOC Lucia Code», .vsix) y pega el token en sus ajustes; o configura Continue, Cline o cualquier cliente compatible con OpenAI con esta dirección y este token.",
        ["DoorBadToken"] = "Falta el token o no es el correcto. Cópialo de sOC Lucia › Ajustes › Editores de código.",
        ["DiagnosticsTitle"] = "Diagnóstico",
        ["OpenEngineLog"] = "Abrir el registro del motor",
        ["OpenDataFolder"] = "Abrir la carpeta de datos",
        ["Accelerator"] = "Motor: llama.cpp {0} · {1}",
        ["WorkMode"] = "Modo agente: la IA resuelve la tarea con herramientas (órdenes, ficheros, internet…), paso a paso, pidiendo permiso",
        ["WorkTitle"] = "Modo agente",
        ["WorkHint"] = "Con «Agente» elegido encima del redactor, la IA puede usar este PC: ejecutar órdenes, leer y escribir ficheros, descargar de internet, usar el portapapeles y abrir cosas. Cada acción se enseña antes de hacerse y la apruebas, salvo que abajo decidas otra cosa. Todo lo que hace queda registrado.",
        ["WorkFolder"] = "Carpeta de trabajo",
        ["WorkFolderPick"] = "Elegir carpeta",
        ["OpenCommandLog"] = "Abrir el registro de acciones",
        ["CommandTitle"] = "¿Ejecutar esta orden?",
        ["CommandIntro"] = "La IA quiere ejecutar esto en tu PC:",
        ["CommandFolder"] = "En: {0}",
        ["CommandAutoApprove"] = "No volver a preguntar en esta conversación",
        ["CommandRun"] = "Ejecutar (Ctrl+Enter)",
        ["CommandRunning"] = "Haciéndolo…",
        ["CommandOutput"] = "Resultado",
        ["WindowsSection"] = "Windows",
        ["TrayOnMinimize"] = "Quedarse en el área de notificación al minimizar",
        ["TrayOnMinimizeHint"] = "Clic en el icono de la bandeja para volver; botón derecho para Abrir o Salir.",
        ["StartWithWindows"] = "Arrancar con Windows",
        ["StartWithWindowsHint"] = "Arranca escondida en el área de notificación al iniciar sesión.",
        ["TrayOpen"] = "Abrir",
        ["TrayExit"] = "Salir",
        ["ModelsFolder"] = "Carpeta de los modelos",
        ["ModelsFolderPick"] = "Elegir otra carpeta (los modelos se mueven allí)",
        ["ModelsFolderHint"] = "Las IA descargadas pesan gigas: pueden vivir en otro disco. Al cambiar la carpeta se mueven las que ya tengas.",
        ["ModelsFolderMoveConfirm"] = "¿Mover {0} fichero(s) de modelo a {1}? La IA se para mientras se mueven.",
        ["ModelsFolderMoving"] = "Moviendo…",
        ["ModelsFolderMovingFile"] = "Moviendo {0}… {1}",
        ["ModelsFolderMoved"] = "Movidos.",
        ["ModelsFolderInside"] = "La carpeta nueva no puede estar dentro de la actual.",
        ["ModelsInstalled"] = "Instaladas en este PC",
        ["ModelActive"] = "En uso",
        ["ModelUse"] = "Usar esta IA",
        ["ModelDelete"] = "Borrar esta IA",
        ["ModelDeleteConfirm"] = "\u00bfBorrar {0} del disco? Se puede volver a descargar.",
        ["EditQuestion"] = "Editar (la copia al redactor)",
        ["ResendQuestion"] = "Volver a enviar",
        ["PcWithGpu"] = "Este PC: {0} ({1} hilos), {2} de RAM, {3} con {4} de memoria de v\u00eddeo.",
        ["PcNoGpu"] = "Este PC: {0} ({1} hilos), {2} de RAM, sin gr\u00e1fica dedicada: la IA va en el procesador.",
        ["PcStarHint"] = "\u2605 = \u00f3ptima para este PC: r\u00e1pida y fiable. Solo se muestran las IA que caben en memoria.",
        ["FitOptimalGpu"] = "\u2605 \u00d3ptima aqu\u00ed: cabe entera en la gr\u00e1fica.",
        ["FitOptimalCpu"] = "\u2605 \u00d3ptima aqu\u00ed: ligera, r\u00e1pida en el procesador.",
        ["FitOkGpu"] = "Funciona, pero m\u00e1s lenta: parte se queda fuera de la gr\u00e1fica.",
        ["FitOkCpu"] = "Funciona, pero m\u00e1s lenta en el procesador.",
        ["FitSlow"] = "Lenta en este PC: cabe en memoria, pero las respuestas tardar\u00e1n.",
        ["PermSection"] = "Permisos",
        ["PermSectionHint"] = "Qu\u00e9 puede usar la IA de este PC en modo agente. \u00abPreguntar\u00bb ense\u00f1a cada acci\u00f3n antes de hacerla; \u00abSiempre\u00bb no pregunta; \u00abNunca\u00bb esconde ese recurso a la IA.",
        ["PermAsk"] = "Preguntar",
        ["PermAllowAlways"] = "Siempre",
        ["PermDeny"] = "Nunca",
        ["Perm_Commands"] = "\u00d3rdenes",
        ["PermHint_Commands"] = "Ejecutar l\u00edneas de PowerShell (programas, git, dotnet, python\u2026).",
        ["Perm_FilesRead"] = "Leer ficheros",
        ["PermHint_FilesRead"] = "Leer ficheros, listar y buscar en carpetas.",
        ["Perm_FilesWrite"] = "Escribir ficheros",
        ["PermHint_FilesWrite"] = "Crear o sobrescribir ficheros (notas, scripts, c\u00f3digo, resultados).",
        ["Perm_Internet"] = "Internet",
        ["PermHint_Internet"] = "Descargar p\u00e1ginas o ficheros de la web (solo lectura).",
        ["Perm_Clipboard"] = "Portapapeles",
        ["PermHint_Clipboard"] = "Leer o sustituir el texto del portapapeles.",
        ["Perm_Apps"] = "Abrir cosas",
        ["PermHint_Apps"] = "Abrir un fichero, carpeta, programa o direcci\u00f3n web con su programa habitual.",
        ["PermTitle"] = "\u00bfPermitir esto?",
        ["PermIntro_Commands"] = "La IA quiere ejecutar esta orden en tu PC:",
        ["PermIntro_FilesRead"] = "La IA quiere leer esto:",
        ["PermIntro_FilesWrite"] = "La IA quiere escribir este fichero:",
        ["PermIntro_Internet"] = "La IA quiere usar internet:",
        ["PermIntro_Clipboard"] = "La IA quiere usar el portapapeles:",
        ["PermIntro_Apps"] = "La IA quiere abrir esto:",
        ["PermConversation"] = "No volver a preguntar por esto en esta conversaci\u00f3n",
        ["PermAlways"] = "Permitir siempre \u00ab{0}\u00bb (se cambia en Ajustes \u203a Permisos)",
        ["PermAllow"] = "Permitir (Ctrl+Enter)",
        ["AskMode"] = "Preguntas",
        ["AskModeHint"] = "Modo preguntas: la IA responde; usa el PC, tus documentos o internet solo si la pregunta lo necesita (pidiendo permiso)",
        ["AgentMode"] = "Agente",
        ["ModelPick"] = "La IA que responde en la aplicaci\u00f3n (las instaladas; m\u00e1s en Ajustes)",
        ["FontSizeHint"] = "Tama\u00f1o del texto de la conversaci\u00f3n (preguntas y respuestas). El resto de la aplicaci\u00f3n no cambia.",
        ["CatalogHf"] = "De Hugging Face",
        ["SearchHf"] = "Buscar m\u00e1s IA en Hugging Face",
        ["SearchHfTip"] = "Nombre o familia: llama, mistral, gemma, qwen, deepseek, spanish\u2026",
        ["SearchHfHint"] = "Busca en huggingface.co por nombre, familia o palabra clave (im\u00e1genes, v\u00eddeo, voz\u2026), pesa cada GGUF y te dice c\u00f3mo ir\u00eda en este PC (\u2605 = \u00f3ptima). Sin la casilla se ven modelos de todo tipo, con enlace; aqu\u00ed solo se instalan los de texto GGUF de un fichero (se elige el Q4_K_M).",
        ["SearchHfSearching"] = "Buscando en Hugging Face y pesando cada resultado\u2026",
        ["SearchHfNone"] = "Nada encontrado. Prueba otro nombre, una familia (llama, qwen, gemma\u2026) o una palabra clave.",
        ["SearchHfFound"] = "{0} resultados: {1} \u00f3ptimos para este PC, {2} que esta aplicaci\u00f3n ejecuta. Orden: primero los \u00f3ptimos, el resto por descargas.",
        ["SearchHfError"] = "No se ha podido buscar: {0}",
        ["SearchHfStats"] = "{0} descargas \u00b7 {1} me gusta",
        ["SearchHfGated"] = "exige aceptar una licencia en huggingface.co (la descarga puede fallar)",
        ["InternetTitle"] = "Permitir que la IA acceda a internet",
        ["InternetHint"] = "En los dos modos puede buscar en la web y leer p\u00e1ginas cuando una pregunta necesita informaci\u00f3n actual o comprobable; cada b\u00fasqueda y p\u00e1gina se ve en la conversaci\u00f3n. Nada m\u00e1s sale del PC. Sin marcar, la IA trabaja sin conexi\u00f3n.",
        ["DocsTitle"] = "Tus documentos",
        ["DocsHint"] = "Deja en esta carpeta ficheros de texto, Markdown, CSV, JSON, c\u00f3digo, HTML o Word (.docx) y la IA los tiene en cuenta (aqu\u00ed guarda tambi\u00e9n los documentos que le pidas, .docx incluido): con cada pregunta recibe los pasajes que encajan con ella, y puede listarlos y leerlos enteros. No se indexa nada fuera del PC.",
        ["DocsPick"] = "Elegir otra carpeta",
        ["DocsOpen"] = "Abrir la carpeta",
        ["DocsCount"] = "{0} documento(s) en cuenta.",
        ["DocsMissing"] = "La carpeta a\u00fan no existe: \u00e1brela para crearla y deja ficheros dentro.",
        ["MemoryTitle"] = "Lo que la IA sabe de ti",
        ["MemoryHint"] = "Frases cortas que la IA guarda cuando le cuentas algo duradero sobre ti (nombre, trabajo, preferencias\u2026). Van con cada conversaci\u00f3n para que no vuelva a preguntarlo. Solo en este PC, en memory.json.",
        ["MemoryEnable"] = "Dejar que la IA recuerde cosas sobre m\u00ed",
        ["MemoryEmpty"] = "Nada todav\u00eda. Ir\u00e1 apareciendo aqu\u00ed seg\u00fan hables.",
        ["MemoryForget"] = "Olvidar esto",
        ["MemoryClear"] = "Olvidarlo todo",
        ["MemoryClearConfirm"] = "\u00bfBorrar todo lo que la IA sabe de ti? En la siguiente conversaci\u00f3n empieza de cero.",
        ["CatalogLabel"] = "Cat\u00e1logo",
        ["SearchOnlyGguf"] = "Solo IA que esta aplicaci\u00f3n puede ejecutar (modelos de texto GGUF)",
        ["SearchNotSingleGguf"] = "GGUF partido en varios ficheros: no se instala desde aqu\u00ed.",
        ["SearchNotGguf"] = "No es un GGUF: esta aplicaci\u00f3n no lo ejecuta (necesita Python u otro programa).",
        ["SearchNotGgufKind"] = "Tipo: {0}. No es un modelo de texto GGUF: esta aplicaci\u00f3n no lo ejecuta (necesita Python u otro programa).",
        ["SearchOpenHf"] = "Abrir en huggingface.co",
        ["FitTooBig"] = "No cabe en la memoria de este PC.",
        ["SaveCode"] = "Guardar como fichero",
        ["OpenDocument"] = "Abrir {0}",
        ["TasksTitle"] = "Tareas programadas",
        ["TasksHint"] = "P\u00eddeselo a la IA en el chat, por ejemplo \u00abcada ma\u00f1ana a las 9 res\u00fameme la carpeta de documentos\u00bb o \u00abrecu\u00e9rdame el viernes a las 18:00 enviar el informe\u00bb: lo programa y se ejecuta solo como una conversaci\u00f3n nueva (\u23F0), mientras la aplicaci\u00f3n est\u00e9 abierta (tambi\u00e9n en la bandeja). Las ejecuciones desatendidas solo usan los recursos puestos en \u00abSiempre\u00bb en Permisos.",
        ["TasksEmpty"] = "No hay tareas programadas.",
        ["TaskEnabled"] = "Activa / parada",
        ["TaskNext"] = "pr\u00f3xima {0}",
        ["TaskLast"] = "\u00faltima {0}",
        ["TaskDelete"] = "Borrar la tarea",
        ["TaskDone"] = "Hecho. Abre la aplicaci\u00f3n para ver el resultado.",
        ["Save"] = "Guardar",
        ["Saved"] = "Guardado",
        ["Ok"] = "Aceptar",
        ["Cancel"] = "Cancelar",
        ["Yes"] = "Sí",
        ["No"] = "No",
        ["Error"] = "Error",
    };

    public static string Language { get; private set; } =
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "es" ? "es" : "en";

    public static event Action? LanguageChanged;

    public static void Use(string language)
    {
        if (language is not ("es" or "en") || Language == language)
            return;
        Language = language;
        LanguageChanged?.Invoke();
    }

    public static string Get(string key)
    {
        var table = Language == "es" ? Spanish : English;
        return table.TryGetValue(key, out var value) ? value
            : English.TryGetValue(key, out var fallback) ? fallback
            : key;
    }

    public static string Format(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), args);
}

/// <summary><c>{loc:T Clave}</c> en el XAML.</summary>
[MarkupExtensionReturnType(typeof(string))]
public sealed class TExtension : MarkupExtension
{
    public TExtension()
    {
    }

    public TExtension(string key) => Key = key;

    [ConstructorArgument("key")]
    public string Key { get; set; } = string.Empty;

    public override object ProvideValue(IServiceProvider serviceProvider) => Loc.Get(Key);
}
